### ISSUE TITLE
Model Selection

### ISSUE THREAD

**Issue by DAYALOKESH** [DAYALOKESH/Network-Intrusion-Detection-System#1]
Currently, we decided to use CNN along with SVM for prediction. but, for model enhancement, better accuracy , and overall model improvement we would like to incorporate a new ML technique alongside.

### Suggestions:

1. Decision Tree
2. Random Forest
3. Any Suggested Technique.

**Comment by DAYALOKESH** [comment]
Look into this, so that we can finalize the Models in Algorithm.

**Comment by jahnavidasari10** [comment]
we can use SVM,KNN,and Naive Bayes also to get a better result.

**Comment by sandeepsanjipogu2002** [comment]
Ok Will look into it

**Comment by DAYALOKESH** [comment]
__Random Forest__ is selected as the Final Model
